[package]
name = "dominote-back-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
dotenvy = "0.15.7"
postgres = "0.19.10"
serde = {version = "1.0.219", features = ["derive"]}
tokio = "1.45.1"
tokio-postgres = "0.7.13"
